api:
  insecure: true
  dashboard: true

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
    network: "project-network"

entryPoints:
  http:
    address: ":80"
  https:
    address: ":433"
